<style type="text/css">

	.custom-navigation ul
	{
		background-color: #ccc; display: inline-block; display: flex; padding: 0; list-style: none;  
	}

	.custom-navigation ul li a{
		background-color: #ff6666;
		padding: 10px;
		display: block;
	}

</style>>

<section class="content-header">
  <h1>
    Customer 
    <small>Management</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
</section>



<section class="content-header">
	<div class="row">
        <div class="col-md-12">
          <div class="box">
            
             
            <div class="box-body custom-navigation">
            	<div class="col-sm-12">
	            	<ul>
	                  	<li>
	                  		<a href="">Menu 1</a>
	                  	</li>

	                  	<li>
	                  		<a href="">Menu 2</a>
	                  	</li>

	                  	<li>
	                  		<a href="">Menu 3</a>
	                  	</li>

	                  	<li>
	                  		<a href="">Menu 4</a>
	                  	</li>
	                 </ul>
              	</div>
              <div class="row">
                <div class="col-md-8">
                  

                </div>
               
              </div>              
            </div>
            <!-- ./box-body -->
            
          </div>
        </div>
    </div>        
</section>





<section class="content">
	<div class="row">
        <div class="col-md-12">
          <div class="box">

         	  <div class="box-header with-border">
              <h3 class="box-title">Customer List</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>

            
              
            <div class="box-body">
              <div class="row">
                <div class="col-md-8">
                  
                  <?php


foreach ($result as $data) {
	//echo $data->customer_account_number;
}

?>

<table border="1">

	<?php
	if($result){?>
	<tr>
		<td>
			Customer Name				
		</td>
		<td>
			Customer Account
		</td>
		<td>
			Customer Phone No
		</td>
		<td>
			Detail
		</td>
		<td>
			Update
		</td>		
	</tr>

	<?php
	foreach ($result as $data) {
	?>

	<tr>
		<td>
			<?php echo $data["customer_name"]; ?>  
		</td>
		<td>
			<?php echo $data["customer_account_number"]; ?>
		</td>
		<td>
			<?php echo $data["customer_phone_primary"]; ?>
		</td>
		<td>
			<a href="<?php echo $this->url('customer',array('action'=>'customerDetail','id'=>$data["id"])) ?>">Detail</a>
		</td>
		<td>
			<a href="<?php echo $this->url('customer',array('action'=>'updatecustomer','id'=>$data["id"])) ?>">Update</a>
		</td>		
	</tr>

	<?php }  /// End foreach

	} else{ ?>

	<tr>
			<td>
				No Customer Found
			</td>
	</tr>
	<?php } ?>
</table>


                </div>               
              </div>              
            </div>
            <!-- ./box-body -->
            
          </div>
        </div>
    </div>        
</section>

